vitruv-tools/Vitruv-CaseStudies

bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations.pcm2java/src-gen/mir/routines/pcm2depInjectJava/.gitignore, bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src-gen/mir/routines/java2PcmClassifier/CreateRepositoryRoutine.java, bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions, bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.pcm2java/src-gen/mir/routines/pcm2java/.gitignore
This PR adds logic for creating a package-info file if it does not yet exist on the creation of the first package in a Java project, so that it can be accessed by the virtual model.
=> Java to PCM Optimization

tests/umlclassumlcomponents/tools.vitruv.applications.umlclassumlcomponents.class2comp.tests/src/tools/vitruv/applications/umlclassumlcomponents/class2comp/tests/InterfaceTest.xtend, tests/umlclassumlcomponents/tools.vitruv.applications.umlclassumlcomponents.comp2class.tests/src/tools/vitruv/applications/umlclassumlcomponents/comp2class/tests/ComponentTest.xtend, tests/umljava/tools.vitruv.applications.umljava.java2uml.tests/src/tools/vitruv/applications/umljava/java2uml/tests/JavaToUmlClassTest.xtend
Reenables several tests cases that were temporarily disabled.
=> Reenable Test Cases

bundles/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/UmlToPcmTypesUtil.xtend, bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlHelper.xtend
Minor optimizations on correspondence handling in applications
=> Application optimizations

bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/common/operators/attribute/AbstractTypeReferenceOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/java/JavaVisibilityHelper.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/pcm/operators/attribute/PcmDataTypeReferenceOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/pcm/operators/attribute/PcmProvidedRolesOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/uml/operators/attribute/UmlGeneralizationsOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/uml/operators/attribute/UmlInterfaceRealizationsOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/uml/operators/attribute/UmlReturnTypeOperator.xtend, bundles/commonalities/tools.vitruv.applications.cbs.commonalities.util/src/tools/vitruv/applications/cbs/commonalities/util/uml/operators/attribute/UmlSingleGeneralizationOperator.xtend, tests/commonalities/tools.vitruv.applications.cbs.commonalities.tests.util/src/tools/vitruv/applications/cbs/commonalities/tests/util/AbstractCBSCommonalitiesExecutionTest.xtend, tests/commonalities/tools.vitruv.applications.cbs.commonalities.tests.util/src/tools/vitruv/applications/cbs/commonalities/tests/util/runner/XtextRunnerWithParameters.xtend, tests/commonalities/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/cbs/java/JavaRepositoryModel.xtend
=> Remove unnecessary modifiers from Xtend code

.project, releng/tools.vitruv.applications.cbs.frameworkwrapper/.classpath, releng/tools.vitruv.applications.cbs.frameworkwrapper/.project, releng/tools.vitruv.applications.cbs.frameworkwrapper/META-INF/MANIFEST.MF, releng/tools.vitruv.applications.cbs.frameworkwrapper/pom.xml, tests/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations.java2pcm.tests/src/tools/vitruv/applications/pcmjava/tests/ejbtransformations/java2pcm/EjbPackageMappingTest.xtend, tests/pcmumlclassjava/tools.vitruv.applications.pcmumlclassjava.tests/src/tools/vitruv/applications/pcmumlclassjava/tests/MediaStoreRepositoryCreationTest.xtend, tests/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.pcm2uml.tests/src/tools/vitruv/applications/pcmumlcomponents/pcm2uml/constructionsimulation/ModelConstructionTest.xtend, tests/umljava/tools.vitruv.applications.umljava.java2uml.tests/src/tools/vitruv/applications/umljava/java2uml/tests/JavaToUmlPackageTest.xtend, tests/umljava/tools.vitruv.applications.umljava.uml2java.tests/src/tools/vitruv/applications/umljava/uml2java/Uml2JavaTransformationTest.xtend
Fixes some more warnings and adds `.project` files for some projects that didn’t have them.
=> Fix more warnings

tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/constructionsimulationtest/JavaConstructionSimulationTest.xtend
see discussion in https://github.com/vitruv-tools/Vitruv/pull/401
=> Disable JavaConstructionSimulationTest

tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/oo/ClassMethodTest.xtend
Reenables a Commonalities test case that was disabled by accident.
=> Reenable Commonalities Test Case

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions, bundles/pcmjava/tools.vitruv.applications.pcmjava.util/src/tools/vitruv/applications/pcmjava/util/java2pcm/Java2PcmPackagePreprocessor.xtend, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.editortests/src/tools/vitruv/applications/pcmjava/pojotransformations/editortests/java2pcm/FieldMappingTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.editortests/src/tools/vitruv/applications/pcmjava/pojotransformations/editortests/java2pcm/Java2PcmPackageMappingTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.editortests/src/tools/vitruv/applications/pcmjava/pojotransformations/editortests/java2pcm/MethodMappingTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/CompositeDataTypeMappingTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/OperationRequiredRoleMappingTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.tests.util/src/tools/vitruv/applications/pcmjava/tests/util/java2pcm/Java2PcmTransformationTest.java, tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/circular/pcmumlclassjava/CompositeDataTypeConceptTest.xtend, tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/circular/pcmumlclassjava/InterfaceConceptTest.xtend
adapts to https://github.com/vitruv-tools/Vitruv/pull/412
=> Adapt to Vitruv’s support for changes affecting multiple resources

bundles/tools.vitruv.applications.pcmumlclass.mapping/src/tools/vitruv/applications/pcmumlclass/mapping/routines.reactions, releng/tools.vitruv.applications.cbs.frameworkwrapper/META-INF/MANIFEST.MF
Adapts to https://github.com/vitruv-tools/Vitruv/pull/449
=> Remove MirBase Dependency

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions, bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations/src/tools/vitruv/applications/pcmjava/depinjecttransformations/pcm2java/PcmJamoppUtilsGuice.xtend, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaSubPackagesOperator.xtend, bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions, bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/Pcm2JavaTransformationTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/RepositoryMappingTransformaitonTest.java, tests/pcmjava/tools.vitruv.applications.pcmjava.tests.util/src/tools/vitruv/applications/pcmjava/tests/util/java2pcm/Java2PcmTransformationTest.java
* Adapts utilities usage to methods moved from framework utils to commons
* Remove some indirections when saving resources and creating URIs
* Improves exceptions throws when invalid states during change propagation occur
=> Utilities Cleanup

tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/PcmUmlClassApplicationTest.xtend
The MediaStore construction simulation test adds references to elements from other resources (and resource sets) during the construction simulation, which currently only works properly because the current UUID resolver implementation resolves the same UUIDs for these elements. For example, a parameter becomes added which references a type in another resource set although it was also created in the resource set in which the parameter is placed.
However, this neither makes sense (as the referenced elements should be those of the same resource set) and will not work properly after merging https://github.com/vitruv-tools/Vitruv/pull/463 anymore.
Since this is a reasonable improvement anyway, merging this PR does not depend on merging https://github.com/vitruv-tools/Vitruv/pull/463 in my …
=> Add Missing Resolution of Elements in Proper Resource Sets

tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/PcmUmlClassApplicationTest.xtend
Fixes remaining issues in the resolution of elements in PCM-UML MediaStore tests. Adapts to and depends on https://github.com/vitruv-tools/Vitruv/pull/466.
=> Correct Element Resolution in PCM-UML Tests

features/tools.vitruv.applications.cbs.commonalities.feature/feature.xml, features/tools.vitruv.applications.pcmjava.ejbtransformations.feature/feature.xml, features/tools.vitruv.applications.pcmjava.feature/feature.xml, features/tools.vitruv.applications.pcmjava.pojotransformations.feature/feature.xml, features/tools.vitruv.applications.pcmumlclass.feature/feature.xml, features/tools.vitruv.applications.pcmumlcomponents.feature/feature.xml, features/tools.vitruv.applications.umlclassumlcomponents.feature/feature.xml, features/tools.vitruv.applications.umljava.feature/feature.xml, features/tools.vitruv.applications.util.temporary.feature/feature.xml
Removes obsolete dependencies of features. Replaces dependencies to framework features with explicit dependencies to plug-ins (for more fine-grained dependency management and compatibility with target platform configurations).
=> Cleanup Feature Dependencies

bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/domaincommon/operators/AbstractTypeReferenceOperator.xtend, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaPackageCompilationUnitsOperator.xtend, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaPackageResourcePathFromNameOperator.xtend, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaSubPackagesOperator.xtend, bundles/tools.vitruv.applications.pcmjava/src/tools/vitruv/applications/pcmjava/java2pcm/TypeReferenceCorrespondenceHelper.xtend, bundles/tools.vitruv.applications.pcmjava/src/tools/vitruv/applications/pcmjava/pcm2java/DataTypeCorrespondenceHelper.xtend, bundles/tools.vitruv.applications.pcmjava/src/tools/vitruv/applications/pcmjava/pcm2java/Pcm2Java.reactions, bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm2uml/PcmDataTypePropagation.reactions, bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaContainerAndClassifierUtil.xtend, tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/PcmUmlClassApplicationTest.xtend
This PR makes small adaptations to conform to the cleanup of the correspondence model in https://github.com/vitruv-tools/Vitruv-Change/pull/22.
=> Adaptation to cleanup of correspondence model

bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/Component.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/ComponentInterface.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/CompositeDataType.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/CompositeDataTypeElement.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/Operation.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/OperationParameter.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/cbs/Repository.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/Class.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/ClassMethod.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/Constructor.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/Interface.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/InterfaceMethod.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/MethodParameter.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/Package.commonality, bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/oo/Property.commonality, bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/DefaultLiterals.java, tests/tools.vitruv.applications.cbs.equivalence.tests/src/tools/vitruv/applications/cbs/equivalencetests/RepositoryEquivalenceTest.xtend
=> Unify capitalization of metamodel imports in Commonalities and Reactions

tests/tools.vitruv.applications.cbs.commonalities.tests/build.properties, tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/CBSCommonalitiesExecutionTest.xtend, tests/tools.vitruv.applications.cbs.equivalencetesttemplates/build.properties, tests/tools.vitruv.applications.demo.familiespersons.tests/build.properties, tests/tools.vitruv.applications.demo.insurancefamilies.tests/build.properties, tests/tools.vitruv.applications.demo.insurancepersons.tests/build.properties, tests/tools.vitruv.applications.pcmjava.tests/build.properties, tests/tools.vitruv.applications.pcmumlclass.tests/build.properties, tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/PcmUmlClassApplicationTest.xtend, tests/tools.vitruv.applications.transitivechange.tests/build.properties, tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/circular/pcmumlclassjava/PcmUmlJavaTransitiveChangeTest.xtend, tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/util/AbstractUmlJavaTest.xtend, tests/tools.vitruv.applications.umljava.tests/build.properties, tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/UmlJavaTransformationTest.xtend
This PR adds required dependencies and build marker files to execute all tests as ordinary JUnit tests rather than plug-in tests, reducing dependencies to Eclipse and improving performance.
=> Execute tests as ordinary JUnit tests

bundles/tools.vitruv.applications.cbs.testutils/.classpath, bundles/tools.vitruv.applications.cbs.testutils/META-INF/MANIFEST.MF, bundles/tools.vitruv.applications.testutility/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.cbs.commonalities.tests/.classpath, tests/tools.vitruv.applications.cbs.commonalities.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.cbs.equivalence.tests/.classpath, tests/tools.vitruv.applications.cbs.equivalence.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.demo.familiespersons.tests/.classpath, tests/tools.vitruv.applications.demo.familiespersons.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.demo.insurancefamilies.tests/.classpath, tests/tools.vitruv.applications.demo.insurancefamilies.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.demo.insurancepersons.tests/.classpath, tests/tools.vitruv.applications.demo.insurancepersons.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.pcmjava.javaeditor.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.pcmjava.tests/.classpath, tests/tools.vitruv.applications.pcmjava.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.pcmumlclass.tests/.classpath, tests/tools.vitruv.applications.pcmumlclass.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.transitivechange.tests/.classpath, tests/tools.vitruv.applications.transitivechange.tests/META-INF/MANIFEST.MF, tests/tools.vitruv.applications.umljava.tests/.classpath, tests/tools.vitruv.applications.umljava.tests/META-INF/MANIFEST.MF
For description, see https://github.com/vitruv-tools/Vitruv-Change/pull/55
=> Use `Import-Package` instead of `Require-Bundle` for JUnit imports

.github/workflows/ci.yml
=> replace GabrielBB/xvfb-action@v1 in ci workflow

tests/tools.vitruv.applications.pcmjava.javaeditor.tests/src/tools/vitruv/applications/pcmjava/javaeditor/java2pcm/Java2PcmTransformationTest.java, tests/tools.vitruv.applications.pcmjava.tests/src/tools/vitruv/applications/pcmjava/tests/pcm2java/Pcm2JavaTransformationTest.xtend, tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/LegacyPcmUmlClassApplicationTest.xtend
Adapts to https://github.com/vitruv-tools/Vitruv-Change/issues/59
=> Make `EChange` generic over its content type

releng/tools.vitruv.casestudies.parent/pom.xml
=> update build parent
