bundles/umljava/tools.vitruv.applications.umljava.util/src/tools/vitruv/applications/umljava/testutil/TestUtil.xtend
bundles/umljava/tools.vitruv.applications.umljava.util/src/tools/vitruv/applications/umljava/util/java/JavaTypeUtil.xtend

I fixed bug in the method `TestUtil.assertTypeEquals()` that lead to an unexpected exception during parameter type comparison, because in `assertTypeEquals()` only classes and not interfaces were considered as possible UML types during dynamic dispatch.
I added the missing dispatch method and a method in `JavaTypeUtil` to retrieve the Interface wrapped in a `TypeReference`.

Fixed bug in TestUtil.assertTypeEquals()

---

bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmRepository.reactions

Fixed a problem with the deletion order in `PcmRepository.reactions` that leads to unnoticed package deletions, since the recorders are not able to record changes to packages whose parent packages are already deleted.

Fixed deletion order problem in PcmRepository.reactions

---

tests/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm.tests/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/AbstractUmlPcmTest.xtend
tests/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm.tests/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/ImportedDataTypesTest.xtend
tests/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm.tests/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/ModelTest.xtend
tests/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm.tests/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/MultiplicityTest.xtend

Due to recent changes in #53, a UML `Model` correspondences not only to a PCM `Repository` but also to the UML `Model` `EClass`. This PR adapts the correspondence claims in tests, which only performed well in recent builds by accident.

Correct UML model correspondence claims

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/.project
bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations.pcm2java/.project
bundles/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations.java2pcm/.project
bundles/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations.pcm2java/.project
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/.project
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.pcm2java/.project
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/.project
bundles/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.pcm2uml/.project
bundles/pcmumlcomponents/tools.vitruv.applications.pcmumlcomponents.uml2pcm/.project
bundles/umlclassumlcomponents/tools.vitruv.applications.umlclassumlcomponents.class2comp/.project
bundles/umlclassumlcomponents/tools.vitruv.applications.umlclassumlcomponents.comp2class/.project
bundles/umljava/tools.vitruv.applications.umljava.java2uml/.project
bundles/umljava/tools.vitruv.applications.umljava.uml2java/.project

This PR removes outdated project filters for the `target` folder, which led to compile errors, because Eclipse projects are now defined to also use the `target` folder of Maven builds.

Remove target folder filters

---

bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions

Fixed a bug in the Java to UML reactions where UML element names were either shortened by one character or completely mutilated during a valid rename change. This was caused by the somewhat careless use of the `replaceFirst()` method that expects regular expressions. Dots were not escaped and therefore led to matching any character. This occurred in two different ways.
1. When the namespace was empty (the `namespacePrefix` was `"."`):
```diff
+   TestSystemImpl
-    estSystemImpl
```
2. When the non-empty namespace matched the name (the `namespacePrefix` was `"TestSystem."`):
```diff
+   TestSystemImpl
-              mpl
```

Fixed character eating UML element rename routine

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.util/META-INF/MANIFEST.MF
bundles/umljava/tools.vitruv.applications.umljava.util/src/tools/vitruv/applications/umljava/util/uml/UmlClassifierAndPackageUtil.xtend
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/java2pcm/PackageMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/java2pcm/TypeReferenceMappingTransformationTest.java

Fixed an issue that prevented the deletion of the persisted Java packages (package info files). Java packages were created twice due to missing correspondences as a result of the Java packages being created by another reaction. As a result, references were overwritten, and the correlating persisted resources of the Java packages not correctly deleted. The unit tests were not able to catch this issue since it only affects the persisted files and not the loaded model (it occurred for the repository concept deletion & renaming test cases). 
This was fixed by attempting to locate the Java packages by name if the correspondence is missing (the find-or-create-pattern, see [PR54](https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/54#discussion_r351258010)). When they …

Fixed broken Java package file deletion

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/META-INF/MANIFEST.MF
bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.util/src/tools/vitruv/applications/pcmjava/util/pcm2java/Pcm2JavaHelper.xtend
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlHelper.xtend
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaHelper.xtend
bundles/umljava/tools.vitruv.applications.umljava.util/META-INF/MANIFEST.MF
bundles/umljava/tools.vitruv.applications.umljava.util/src/tools/vitruv/applications/umljava/util/java/JavaContainerAndClassifierUtil.xtend

This pull request resolves more problems with the duplicated creation of Java/UML types by applying the find-or-create-pattern ([see PR54](https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/54#discussion_r351258010)) to both class and interface creation across the reactions. 
This solves the issue of signature, attribute, and parameter concept tests crashing during the test setup since they originally did find two instances when resolving via the correspondences.
This pull request also addresses another issue where newly created Java compilation units were not added to the reference of their packages in the PCM to Java reaction file. This is required to enable the find or create pattern.

Fixed more problems with duplicate Java/UML type creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmRepository.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryAndSystemPackage.reactions
bundles/util/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/pcm/PcmRepositoryUtil.xtend

Prevented duplicate repository creation with the find-or-create pattern. Existing repositories are matched by name and retrieved with a newly added repository `EClass` correspondence that is now always inserted when creating a repository.

Fixed a problem with duplicate repository creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/util/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaContainerAndClassifierUtil.xtend

Fixed an issue where the change propagation crashed because the Java to PCM reactions did not expect the edge case `null` as a value for Java package names, which means the package is unnamed. This can only appear during transitive scenarios, not with the Java to PCM reactions alone.

Fixed inability to deal with null-names when reacting to the creation of Java packages

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlInterface.reactions

Fixed a problem with duplicate operation interface creation in the PCM model. A second operation interface was created due to the existing operation interface missing the required correspondences. This could be fixed by implementing the find-or-create-pattern in the Java-to-PCM reactions. Interestingly, the UML-to-PCM reactions already had the pattern implemented.
It is important to note that it seems like the Java-to-PCM reactions assume there is only one Repository existing at a time, which is different from UML-to-PCM which does not explicitly make that assumption. I am not sure if these reactions are required to handle multiple repositories, but one can and the other explicitly cannot.
Furthermore, the Java-to-PCM interface routines cover a case where the user can decide to create a …

Fixed duplicate operation interface creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmMethod.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryAndSystemPackage.reactions
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/java2pcm/PackageMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.tests.util/src/tools/vitruv/applications/pcmjava/tests/util/Pcm2JavaTestUtils.java

Prevented invalid repository name propagation by enforcing the required naming rule:
```java
pcmRepository.entityName = javaPackage.name.toFirstUpper
```
This rule is part of the following connections:

Fixed a problem with repository name propagation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmSystem.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryAndSystemPackage.reactions
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.pcm2java.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/system/SystemMappingTransformationTest.java

Prevented duplicate PCM system creation by implementing the find-or-create-pattern and adding system `EClass` correspondences to enable locating existing systems.
Similar to the find-or-create-pattern of repositories (see [PR69](https://github.com/vitruv-tools/Vitruv-Applications-ComponentBasedSystems/pull/69#issuecomment-578171304)), we are matching first case upper AND lower case names when trying to locate an existing system, since both could be possible.

Fixed duplicate system creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmMethod.reactions

Multiple issues were caused by the naive rename routine that just renamed every `pcm::NamedElement` corresponding to a `java::NamedElement`:
```java
pcmElement.entityName = javaElement.name
```
While this worked for the Java to PCM reactions on their own, it did not work in combination with other reactions as they introduce correspondences between elements that should not be renamed together.
These are some of the issues observed in the transitive scenario:
-  Loops that endlessly appended `.java` to the names of compilation units and corresponding PCM and UML elements
-  Loops that endlessly appended `Impl` to the names of classes and corresponding PCM and UML elements
- PCM repositories renamed to `"datatypes"` as their subpackages correspond to the PCM element
- Invalid first letter …

Fixed incorrect Java to PCM name change propagation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryComponentPackage.reactions

Prevented the duplicate creation of repository components by implementing the find-or-create-pattern. For UML to PCM, this was already implemented. For Java to PCM, a special case was required to ensure the creation of repository components even when there was no containing Java package. In this special case, finding existing repository components is not possible. Therefore they are always created.

Fixed duplicate repository component creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmRepositoryComponent.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmSystem.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlIPREClass.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryComponentPackage.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaMethod.reactions
bundles/util/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaContainerAndClassifierUtil.xtend
bundles/util/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/uml/UmlClassifierAndPackageUtil.xtend

This pull request restores the consistent capitalization for repository components and classifiers in the fully transitive case between PCM, UML, and Java.
Even when an incorrectly capitalized name was propagated and then later corrected, it could result in problems depending on the execution order of the transformations. This led, amongst other problems, to duplicate element creation due to mismatching names.
This was fixed by enforcing the required capitalization in routines that assumed the capitalization of the source element was correct and therefore did not enforce any naming scheme. In a non-transitive scenario, these problems do not occur as the source element always conforms to the assumed naming schemes.

Fixed incorrect name propagation for repository components and classifiers

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlCompositeDataTypeClass.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions

I fixed duplicate CompositeDataType creation by implementing the find-or-create-pattern in the Java-to-PCM reactions. This was done for both composite and collection data types. I also implemented a rename routine that renames PCM composite and collection data types when Java classes are renamed. This renaming is not a functionality that is required by the Java-to-PCM test cases, but it missing could lead to problems later on. This pull request also includes some smaller syntactical fixes.

Fixed duplicate CompositeDataType creation

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations.pcm2java/src/tools/vitruv/applications/pcmjava/depinjecttransformations/pcm2java/Pcm2JavaDepInject.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.java2pcm/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmMethod.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmAssemblyContext.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlAssemblyContextProperty.reactions
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlAttribute.reactions
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaAttribute.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaMethod.reactions

I fixed the duplicate creation of assembly contexts and correlating fields, constructors, import declarations, and access methods. This prevents several problems that appear during the assembly context concept propagation, mainly duplicate creation, overwriting and incorrect name propagation.
This was fixed by implementing the find-or-create-pattern for:
- Fields, constructors, and import declarations in the PCM-to-Java reactions
- Assembly contexts in the Java-to-PCM reactions
- Attributes of Classes and Enums in the Java-to-UML reactions
- Fields of Classes and Enums in the UML-to-Java reactions
- Methods (including constructors) of Classes, Interfaces, and Enums in the Java-to-UML reactions
- Methods (including constructors) of Classes, Interfaces, and Enums in the UML-to-Java …

Fixed the duplicate creation of the assembly context concept elements

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmProvidedRole.reactions
bundles/pcmumlclass/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlProvidedRoleRealization.reactions
bundles/umljava/tools.vitruv.applications.umljava.java2uml/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/umljava/tools.vitruv.applications.umljava.uml2java/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions

I fixed a problem with endless provided role generation by implementing the find-or-create-pattern for provided roles and interface realizations. The pattern avoids duplicate creation which enabled the change propagation loop. I also solved two problems by ensuring proper deletion of the type references that represent realization relations. First, the problem of uncontained reference objects and, second, the problem of duplicate references due to the creation of a semantically identical type reference after the improper deletion of the original one. Depending on the execution order, either one of these problems appeared.

Fixed incorrect creation and adaption of provided roles

---

tests/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations.java2pcm.tests/src/tools/vitruv/applications/pcmjava/tests/ejbtransformations/java2pcm/EjbPackageMappingTest.xtend

Readds imports that were accidentally removed in #86 leading to compile errors.

Readd accidentally removed imports

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations/src/tools/vitruv/applications/pcmjava/depinjecttransformations/pcm2java/Pcm2JavaDepInject.reactions
releng/tools.vitruv.applications.cbs.parent/pom.xml
tests/pcmjava/pom.xml

* Upgrade parent POM to 1.1.0 (predefines Tycho 2.2)
* Removes dependency to to-be-removed util
* Enables UI harness with marker files (introduced with new parent POM) instead of manual Maven configuration

Parent POM 1.1.0 Upgrade

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions

I found this missing use case while working on my equivalence tests. 
I have not written a unit test, but this change will at least partially be covered by the equivalence tests.

Reactions: React to PCM Repository deletion

---

bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaMemberAndParameterUtil.xtend

Fixed setter parameter name not renamed to new attribute name when renaming a java attribute.

Reactions: Adjust Java setter parameter name after Java attribute name changed

---

bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml/UmlRepositoryComponentPackage.reactions

If a user creates the datatypes and contracts subpackages manually, the UML reactions should detect that (currently they ask what kind of component they should represent).
Reasons: 
a) that’s how the Java<->PCM reactions do it
b) if we _produce_ this structure after a Repository was created, we should also _consume_ this structure to create repository

Reactions: Detect Repository Subpackages in UML

---

bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm/PcmRepository.reactions

The reaction was also triggered when moving a repository file.

PCM->UML: React to Repository Deletion Instead of Root Removal

---

bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions

This PR fixes some minor problems leading to errors when using UML-Java Reactions as a bidirectional transformation.
* Ensure that already performed name changes are not processed again in the opposite direction
* Ensure that a Java class created for a UML data type is not mapped to a UML class again

Uml-Java Improvements

---

tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/pcmumlclassjava/MediaStoreRepositoryCreationTest.xtend

This PR removes setting a dialog-based user interactor and the according necessity to manually perform user interactions in MediaStore tests for transitive change propagation.
The tests did not work properly before (even not with manual interaction), so we need to fix them anyway. At the same time, we can add predefined user interactions, because it should not be necessary to manually perform user interactions while all other model changes are performed automatically.
This PR adapt to the reduction of the `VirtualModel` interface in https://github.com/vitruv-tools/Vitruv/pull/406.

Remove Manual User Interaction from MediaStore Tests

---

tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/CBSCommonalitiesExecutionTest.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/cbs/java/JavaCompositeDataTypeTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/cbs/java/JavaOperationTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/oo/java/JavaClassMethodTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/oo/java/JavaClassPropertyTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/oo/java/JavaConstructorTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/oo/java/JavaInterfaceMethodTestModels.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/util/VitruvApplicationTestAdapter.xtend
tests/tools.vitruv.applications.cbs.commonalities.tests/src/tools/vitruv/applications/cbs/commonalities/tests/util/java/JavaTestModelsBase.xtend

Together with https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/pull/88, this brings the execution time of the Commonalities tests down to 2m58s from 4m59s on my machine.

Do not Resolve Java Types in Foreign Resource Sets

---

bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaAttribute.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaMethod.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaTag.java
bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaMemberAndParameterUtil.xtend

Currently, the UML -> Java reactions use heuristics to find the getters and setters of some attribute. However, we already have a construct to model this explicitly, namely *tagged correspondences*. This pull request updates the existing reactions to use correspondences for getters and setters.
By using explicit correspondences, we do not need to iterate over all methods of some class to find the possibly existing accessors and can correctly react to more actions like a rename of an accessor.
Furthermore, for future work we could identify getters / setters in Java -> UML transformations and create a correspondence to the correct UML attribute. Currently, when creating a Java accessor method, a UML method is created.

Use correspondences for Java Accessors

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations/src/tools/vitruv/applications/pcmjava/depinjecttransformations/pcm2java/Pcm2JavaDepInject.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations/src/tools/vitruv/applications/pcmjava/ejbtransformations/pcm2java/Pcm2EjbJava.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.util/src/tools/vitruv/applications/pcmjava/util/java2pcm/TypeReferenceCorrespondenceHelper.xtend
bundles/pcmjava/tools.vitruv.applications.pcmjava.util/src/tools/vitruv/applications/pcmjava/util/pcm2java/DataTypeCorrespondenceHelper.xtend
bundles/tools.vitruv.applications.cbs.commonalities/META-INF/MANIFEST.MF
bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaPackageCompilationUnitsOperator.xtend
bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaSubPackagesOperator.xtend
bundles/tools.vitruv.applications.cbs.commonalities/src/tools/vitruv/applications/cbs/commonalities/java/operators/JavaVisibilityConditionOperator.xtend
bundles/tools.vitruv.applications.pcmumlcomponents/src/tools/vitruv/applications/pcmumlcomponents/pcm2uml/PcmToUml.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaContainerAndClassifierUtil.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/circular/pcmumlclassjava/SystemConceptTest.xtend

Fixes several shortcomings of the diverse transformations.
- Matches an existing package realizing a component in PCM->Java. By now, a package was created again, which did not lead to a failure because resolution was performed by TUIDs which are the same. Moving to UUIDs, this implementation leads to a failure.
- Properly sets the name of a `CompilationUnit`. In several cases, we set the `name` to the file name instead of the fully qualified name. Although JaMoPP accepts and properly serializes that, JaMoPP actually loads `CompilationUnit`s with a fully qualified `name`, such that several checks fail or workarounds have been built.
- Checks Java namespaces for equivalence before removing and inserting the same ones.
- Fixes a mistakes in the test for PCM systems transformed to Java, which …

Transformation Fixes

---

tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.editortests/src/tools/vitruv/applications/pcmjava/pojotransformations/editortests/java2pcm/FieldMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.editortests/src/tools/vitruv/applications/pcmjava/pojotransformations/editortests/java2pcm/MethodMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/CompositeDataTypeMappingTransformationTest.java
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/ComponentTest.xtend

Depends on https://github.com/vitruv-tools/Vitruv/pull/435 and adapts to the removal of the `TransactionalEditingDomain` and related interface methods.

Remove Transactional Change Executions

---

tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaPackageTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaPackageTest.xtend

Check (non-)existence of a package before and after its deletion through change propagation.
It especially prepares for the correspondence model requiring UUIDs for objects (https://github.com/vitruv-tools/Vitruv/pull/438), as correspondence resolution for deleted objects will throw an exception then.

Improve Validation of Package Deletion

---

bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/DefaultLiterals.java
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm2uml/PcmRepository.reactions
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/Pcm2JavaTransformationTest.java
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlPackageTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlPackageTest.xtend

Minor improvements to the removal of packages (leads to missing UUIDs after merging https://github.com/vitruv-tools/Vitruv/pull/438 otherwise) and messages and checks in tests.

Correct UML Repository Package Removal and Improve Tests

---

bundles/tools.vitruv.applications.umlclassumlcomponents/src/tools/vitruv/applications/umlclassumlcomponents/class2comp/class2comp.reactions
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/AbstractClass2CompTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/Class2CompIntegrationTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/ClassTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/DataTypeTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/InterfaceTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/ModelTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/PackageTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/class2comp/VisibilityTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/AbstractComp2ClassTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/Comp2ClassIntegrationTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/ComponentTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/DataTypeTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/InterfaceTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/ModelTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/comp2class/VisibilityTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/util/AbstractUmlClassCompTest.xtend
tests/tools.vitruv.applications.umlclassumlcomponents.tests/src/tools/vitruv/applications/umlclassumlcomponents/tests/util/SharedTestUtil.xtend

This PR fixes some issues in the UML class-components application (although they are still in a rather immature state):
* Create and retrieve correspondences only via Reactions language constructs. By now, manual correspondences were created and not necessarily resolved correctly
* Propagate renaming of packages to components
* React to the renaming of data types
The focus of this PR, however, is the rewrite of tests between UML classes and components. Some of them were hard to fix to be compatible with https://github.com/vitruv-tools/Vitruv/pull/438, such that this PR completely replaces the existing tests using the `VitruvApplicationTest` rather than the `LegacyVitruvApplicationTest`. This especially ensure that:
* The `CorrespondenceModel` is not accessed in the test anymore
* No …

UML Class-Components Fixes and Transaction Tests

---

bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlTypePropagation.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaTypePropagation.reactions

Currently, the UML-Java transformations create a new type reference on every change, even if the type reference stays the same. This especially violates hippocraticness of the bidirectional transformation between UML and Java, because adding a type reference in Java and propagating it to UML will result in overwriting the Java type reference again by the inverse direction transformation.
This PR fixes that and reuses the existing type reference.

Reuse Existing Type References in UML-Java

---

tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/circular/pcmumlclassjava/RepositoryConceptTest.xtend

This PR reenables the test case disabled in #131. The reason for failing seems to related to system/environment specifics. We investigate the cause and how to solve it in this PR.

Reenable Test Case

---

bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaStandardType.xtend
bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaTypeUtil.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlAttributeTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlClassMethodTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlClassTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlEnumTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlInterfaceMethodTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlInterfaceTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/pcmumlclassjava/MediaStoreRepositoryCreationTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaAssociationTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaAttributeTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaClassMethodTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaEnumTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaInterfaceMethodTest.xtend
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/uml2java/UmlToJavaParameterTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlAttributeTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlClassMethodTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlClassTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlEnumTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlInterfaceMethodTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlInterfaceTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaAssociationTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaAttributeTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaClassMethodTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaEnumTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaInterfaceMethodTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaParameterTest.xtend

Unifies the namespace reference helper methods to only use those of the Java domain rather than the ones from the temporary util package.
Relates to #3 
Relates to (but does not require) [Vitruv-Domains-ComponentBasedSystems#103](https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/pull/103)

Cleanup Java namespace helper methods

---

bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaPackageTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/util/TestUtil.xtend

This PR ensures that UML package names starting uppercase are transformed into packages starting lowercase in Java. It also adds test cases for that situation.
It prepares for #160 to also work on Windows-based systems, as the uppercase tests do not work there properly because of different handling of differences in capitalization in Windows and Unix file systems.

Properly Transform Package Names Starting Uppercase in UML

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm2uml/PcmRepository.reactions
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml2pcm/UmlRepositoryAndSystemPackage.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/Pcm2JavaTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/OperationProvidedRoleMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.tests.util/src/tools/vitruv/applications/pcmjava/tests/util/java2pcm/Java2PcmTransformationTest.java
tests/tools.vitruv.applications.transitivechange.tests/src/tools/vitruv/applications/transitivechange/tests/linear/java2uml/JavaToUmlPackageTest.xtend

This PR provides minor improvements to the transformations that will lead to errors as soon as correspondence handling within the framework is corrected. Currently, some correspondences are removed unintendedly, because _every_ correspondence of a an element removed by a Reactions is removed, thus even the correspondences to completely different domains. For example, when removing a PCM repository leading to a UML package removal, this will erroneously also remove the correspondence between the UML package and the Java package.
After fixing that framework ug, some actual bugs in the transformations will lead to failures that were hidden because of accidentially removed correspondences before. This PR prepares for that and provides some additional improvements.
* Reactions now remove …

Correspondence-Related Transformations Improvements

---

.mvn/extensions.xml
.mvn/wrapper/maven-wrapper.properties
releng/tools.vitruv.applications.cbs.parent/pom.xml

Upgrades parent POM to 1.3.0 (Eclipse 2021-06).
Improves dependency to Tycho 2.3.0 and uses Maven 3.8.1.
Improves Palladio dependency to 5.0.0.
Fixes a bug caused by an incompatibility between Xtext and JDT in Eclipse 2021-06 repository.

Eclipse 2021-06

---

.github/workflows/ci.yml

Add workflow_dispatch event to the CI workflow to enable [manual workflow execution](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#manual-events).

Add workflow_dispatch event to the CI workflow

---

bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlAttribute.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions
bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/java/JavaModifierUtil.xtend

This PR fixes the behaviour of Java to UML reactions to be independent of the order of changes. 
In Java, visibility is modelled by placing an instance of a visibility class (`Private`, `Protected`, or `Public`) in the `annotationsAndModifiers` collection of the element. To update the visibility, the previous visibility is removed from the collection and the new visibility is inserted. The previous implementation assumed the remove -> insert order while insert -> remove might be possible too (i.e. is occurring when deriving changes using the state-based API). 
Furthermore replaces some compound triggers in trivial reactions by an atomic trigger as suggested in #103.

Fixed Java to UML element visibility reactions dependability on change order

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations/src/tools/vitruv/applications/pcmjava/pojotransformations/java2pcm/Java2PcmClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
bundles/tools.vitruv.applications.util.temporary/src/tools/vitruv/applications/util/temporary/uml/UmlClassifierAndPackageUtil.xtend
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/Pcm2JavaTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/BasicComponentMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/CompositeComponentMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/OperationInterfaceMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/OperationProvidedRoleMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/PcmParameterMappingTransformationTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/repository/RepositoryMappingTransformaitonTest.java
tests/pcmjava/tools.vitruv.applications.pcmjava.pojotransformations.tests/src/tools/vitruv/applications/pcmjava/tests/pojotransformations/pcm2java/system/SystemMappingTransformationTest.java
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/java2uml/JavaToUmlEnumTest.xtend
tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/uml2java/UmlToJavaAttributeTest.xtend

This PR removes correspondences to `Java::CompilationUnit` from UML <-> Java and PCM <-> Java. Additionally, minor improvements to the reactions and tests are added.
Each Java `Classifier` (`Class`, `Interface`, or `Enum`) is contained in a `CompilationUnit`. A `CompilationUnit` represents the actual Java file. In the current consistency implementations, every element corresponding to a `Classifier` (e.g. a UML class) has a correspondence to its corresponding Java classifier and the classifier's compilation unit. This PR simplifies this such that only one correspondence is created, the one between the classifier and the corresponding element.
A `CompilationUnit`, i.e. the file, might be empty. This cannot be modelled with the old setup.
Since any Java classifier has exactly one …

Remove Correspondence setup to Java::CompilationUnit

---

tests/tools.vitruv.applications.umljava.tests/src/tools/vitruv/applications/umljava/tests/util/JavaUmlViewFactory.xtend

Adapts the application framework to changes performed in [Vitruv#492](https://github.com/vitruv-tools/Vitruv/pull/492).
1) Some testing functionality for views was integrated into the core framework, thus the `JavaUmlViewFactory` is adjusted to reuse these.

Adapt to moving of state-based propagation into views

---

releng/tools.vitruv.applications.cbs.parent/pom.xml

This PR adds a local build Maven profile as described in [Vitruv#510](https://github.com/vitruv-tools/Vitruv/issues/510).
`mvn clean verify -Dvitruv.framework.path='<path_to_vitruv_folder>' -Dvitruv.domains.path='<path_to_domains_folder>'`
Both arguments are optional, i.e. the nightly update site of the framework but the local domains repository can also be combined.

Add local build Maven profile

---

.github/workflows/ci.yml

Updates versions of used GitHub actions.
Change is performed to be in sync with [Vitruv#525](https://github.com/vitruv-tools/Vitruv/pull/525) and [Vitruv-Domains-CBS#117](https://github.com/vitruv-tools/Vitruv-Domains-ComponentBasedSystems/pull/117).

Update referenced GitHub actions versions

---

releng/tools.vitruv.applications.cbs.parent/pom.xml

This PR adds a property for the DSLs updatesite repository, such that it can be referenced in a local build of that site.
All updatesite URLs now default to the Vitruv nightly updatesite, as this is provided as an aggregate now.

Add DSLs updatesite and path parameter

---

releng/tools.vitruv.applications.cbs.parent/pom.xml

This PR removes the aggregated updatesite generation from the build, as it is built for the complete Vitruv project in the [updatesite](https://github.com/vitruv-tools/updatesite) repository upon deploying new artifact versions.

Adapt to framework and domains not providing an aggregated updatesite

---

releng/tools.vitruv.applications.cbs.parent/pom.xml

The aggregated Vitruv updatesite was referenced in the build to resolve the dependencies of the Vitruv projects. This is error prone, because, e.g., when removing a bundle in this project it can still be resolved in the aggregated updatesite, thus leading to a successful build although it should actually fail. Thus, this PR makes the updatesites providing dependencies explicit rather than resolving them transitively using the aggregated Vitruv updatesite.

Replace aggregated Vitruv updatesite with updatesites of dependencies

---

tests/pcmjava/tools.vitruv.applications.pcmjava.tests.util/src/tools/vitruv/applications/pcmjava/tests/util/java2pcm/Java2PcmTransformationTest.java

This is preparatory work for removing the `PropagatedChangeListener` by integrating the required functionality into the `ChangePropagationListener` interface.

Adapt to modified change propagation listener interface

---

bundles/pcmjava/tools.vitruv.applications.pcmjava.common/src/tools/vitruv/applications/pcmjava/common/pcm2java/Pcm2JavaCommon.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.depinjecttransformations/src/tools/vitruv/applications/pcmjava/depinjecttransformations/pcm2java/Pcm2JavaDepInject.reactions
bundles/pcmjava/tools.vitruv.applications.pcmjava.ejbtransformations/src/tools/vitruv/applications/pcmjava/ejbtransformations/pcm2java/Pcm2EjbJava.reactions
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml2pcm/UmlRepositoryAndSystemPackage.reactions
bundles/tools.vitruv.applications.pcmumlcomponents/src/tools/vitruv/applications/pcmumlcomponents/pcm2uml/PcmToUml.reactions
bundles/tools.vitruv.applications.pcmumlcomponents/src/tools/vitruv/applications/pcmumlcomponents/uml2pcm/UmlToPcm.reactions
bundles/tools.vitruv.applications.umlclassumlcomponents/src/tools/vitruv/applications/umlclassumlcomponents/class2comp/class2comp.reactions
bundles/tools.vitruv.applications.umlclassumlcomponents/src/tools/vitruv/applications/umlclassumlcomponents/comp2class/comp2class.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlAttribute.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions

Removes compound change triggers from all application tests in preparation to removing compound triggers from the language at all. The rationale behind this in discussed in [Vitruv-DSLs#32](https://github.com/vitruv-tools/Vitruv-DSLs/issues/32).
There are only two supported compound triggers: `created and inserted in <container>` and `deleted and removed from <container>`. Those were refactored as follows:
- `created and inserted` was changed to `inserted` for all occurrences
- `deleted and removed` was changed to `deleted` if the element has an identity that is not bound to its container and thus no context information is needed (like `PCM:RepositoryComponent`) and `removed` otherwise (like `PCM:Parameter`)

Remove usage of compound reactions triggers

---

.github/workflows/ci.yml

Similar to [Maven-Build-Parent#26](https://github.com/vitruv-tools/Maven-Build-Parent/pull/26), this PR adapts the release process to create a release after a GitHub release is created instead of depending on tags.
Changes are identical to [Vitruv-Change#17](https://github.com/vitruv-tools/Vitruv-Change/pull/17) where trigger got tested.

Deploy release version after creating a GitHub release

---

tests/tools.vitruv.applications.pcmjava.javaeditor.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.pcmjava.javaeditor.tests/src/tools/vitruv/applications/pcmjava/javaeditor/java2pcm/CompilationUnitManipulatorHelper.java
tests/tools.vitruv.applications.pcmjava.javaeditor.tests/src/tools/vitruv/applications/pcmjava/javaeditor/java2pcm/Java2PcmTransformationTest.java

This PR removes the Java builder from the Java-PCM editor tests and triggers change propagation explicitly rather than waiting for the project build. In effect, this should resolve the problem of undetermistic test failures and thus fixes #206.
The `Java2PcmTransformationTest` is only adapted as far as necessary to remove the Java builder. It does not address the tests themselves (which may also require some code quality improvements).
The tests still implement the `LegacyVitruvApplicationTest`, which has to be replaced in the future. But the tests do not trigger a project build to have the Java builder perform change propagation anymore, but edits in the tests are tracked and resulting difference sbetween the resources are then calculated by the …

🚀 Fix indeterministic test failures by explicitly triggering change propagation in Java-PCM tests

---

bundles/tools.vitruv.applications.pcmjava/src/tools/vitruv/applications/pcmjava/java2pcm/Java2PcmClassifier.reactions
bundles/tools.vitruv.applications.pcmjava/src/tools/vitruv/applications/pcmjava/pcm2java/Pcm2Java.reactions
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/pcm2uml/PcmRepository.reactions
bundles/tools.vitruv.applications.pcmumlclass/src/tools/vitruv/applications/pcmumlclass/uml2pcm/UmlRepositoryAndSystemPackage.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/java2uml/JavaToUmlMethod.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaClassifier.reactions
bundles/tools.vitruv.applications.umljava/src/tools/vitruv/applications/umljava/uml2java/UmlToJavaMethod.reactions

Adapts to referencing a potentially corresponding element in the precondition `with` block of a correspondence retrieval with the name `it` introduced in vitruv-tools/Vitruv-DSLs#49.

Adapt to changes parameter name in retrieval precondition methods

---

.mvn/extensions.xml
.mvn/wrapper/maven-wrapper.properties
bundles/tools.vitruv.applications.cbs.commonalities/META-INF/MANIFEST.MF
bundles/tools.vitruv.applications.pcmjava/META-INF/MANIFEST.MF
bundles/tools.vitruv.applications.pcmumlclass/META-INF/MANIFEST.MF
bundles/tools.vitruv.applications.umljava/META-INF/MANIFEST.MF
bundles/tools.vitruv.applications.util.temporary/META-INF/MANIFEST.MF
features/tools.vitruv.applications.cbs.commonalities.feature/feature.xml
features/tools.vitruv.applications.pcmjava.feature/feature.xml
features/tools.vitruv.applications.pcmumlclass.feature/feature.xml
features/tools.vitruv.applications.umljava.feature/feature.xml
features/tools.vitruv.applications.util.temporary.feature/feature.xml
pom.xml
releng/tools.vitruv.applications.cbs.updatesite/category.xml
releng/tools.vitruv.applications.cbs.updatesite/pom.xml
releng/tools.vitruv.casestudies.dependencywrapper/META-INF/MANIFEST.MF
releng/tools.vitruv.casestudies.dependencywrapper/pom.xml
releng/tools.vitruv.casestudies.parent/pom.xml
tests/tools.vitruv.applications.cbs.commonalities.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.demo.familiespersons.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.demo.insurancefamilies.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.demo.insurancepersons.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.pcmjava.javaeditor.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.pcmjava.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.pcmumlclass.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.transitivechange.tests/META-INF/MANIFEST.MF
tests/tools.vitruv.applications.umljava.tests/META-INF/MANIFEST.MF

Improve dependencies for Eclipse 2022-06 updating parent POM to 2.0.0. New parent POM defaults to non-platform tests, thus marker files can be removed.
Due to breaking changes, we bump the development version from 2.1.0 to 3.0.0

Eclipse 2022-06

---

.github/workflows/ci.yml
bundles/tools.vitruv.applications.cbs.testutils/src/tools/vitruv/applications/cbs/testutils/equivalencetest/DefaultEquivalenceTestBuilder.xtend

This PR adds support to run the validation GitHub Actions on all major OS (Linux, Windows, macOS).
Releases are still built and released on Ubuntu only.
For now, Windows builds are disabled as they fail. This behavior is documented #241.
⚠️ Before merging this, the branch protection rules need to be adjusted to the modified jobs ⚠️
Follows [Vitruv-Change#24](https://github.com/vitruv-tools/Vitruv-Change/pull/24)

Run CI builds on all major OS

---

tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/InterfaceConceptTest.xtend
tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/PcmUmlElementEqualityValidation.xtend
tests/tools.vitruv.applications.pcmumlclass.tests/src/tools/vitruv/applications/pcmumlclass/tests/RepositoryComponentConceptTest.xtend

This pull request follows issue https://github.com/vitruv-tools/Vitruv-CaseStudies/issues/242 , which mentions only part of the PCM-UML-tests are updated to the ViewBasedVitruvApplicationTest. This pull request is to update another class, RepositoryComponenConceptTest, to Viewbased.

Update RepositoryCopmonentConceptTest in PCM-UML-tests to viewbased

---

.github/workflows/ci.yml

In preparation for migrating to Java 17, this PR already updates the CI to use Java 17 for building in source compatibility mode for Java 11 (as specified in [Maven Build Parent](https://github.com/vitruv-tools/Maven-Build-Parent)).
Additionally, the Java distribution is changed to the Eclipse distribution temurin.

Migrate to Java 17 CI actions

---

tests/tools.vitruv.applications.cbs.equivalence.tests/src/tools/vitruv/applications/cbs/equivalencetests/RepositoryEquivalenceTest.xtend

This PR adapts to tracking cascade deletions. In general, there should be no adaption needed as the changes should not affect any use case. By tracking cascade deletions however, incorrect behavior in the equivalence tests became apparent. By reloading the Java files, additional layout information children are created per resource which are absent for the in-memory preserved resources of the V-SUM. As such, `propagateChanges` tries to delete these layout information but the V-SUM fails to resolve them, leading to test failures.
The correct behavior here would be to load the resources ignoring the layout information - as is already done e.g. in the Java Construction Simulation of UML<-> Java. However, the test view currently does not provide the functionality to define load options. This …

Adapt to tracking cascade deletions

---

bundles/tools.vitruv.applications.cbs.testutils/.classpath
tests/tools.vitruv.applications.cbs.commonalities.tests/.classpath
tests/tools.vitruv.applications.cbs.equivalence.tests/.classpath
tests/tools.vitruv.applications.demo.familiespersons.tests/.classpath
tests/tools.vitruv.applications.demo.insurancefamilies.tests/.classpath
tests/tools.vitruv.applications.demo.insurancepersons.tests/.classpath
tests/tools.vitruv.applications.pcmjava.tests/.classpath
tests/tools.vitruv.applications.pcmumlclass.tests/.classpath
tests/tools.vitruv.applications.transitivechange.tests/.classpath
tests/tools.vitruv.applications.umljava.tests/.classpath

This PR adds JUnit 5 to all test projects' classpaths, thus fixing the Xtend errors occurring with Xtend 2.29 and Eclipse 2022-12.
https://github.com/vitruv-tools/.github/issues/10

Fix Xtend error
